[cerebrium.deployment]
name = "image-classification-deploy"
python_version = "3.9"
include = ["./*"]
exclude = [
    "venv/*",
    ".git/*",
    "*.pyc",
    "__pycache__/*",
    ".pytest_cache/*",
    "*.log",
    "logs/*",
    "models/pytorch_model_weights.pth",
    "models/model.onnx"
]

[cerebrium.hardware]
cpu = 2
memory = 4.0
compute = "CPU"
gpu_count = 0
provider = "aws"
region = "us-east-1"

[cerebrium.runtime.custom]
port = 8000
healthcheck_endpoint = "/health"
dockerfile_path = "./Dockerfile"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 5
cooldown = 30
replica_concurrency = 100