[cerebrium]
name = "image-classification-model"
description = "ImageNet classification using ONNX model"
include = [
    "src/",
    "models/",
    "assets/",
    "requirements.txt",
    "Dockerfile"
]
exclude = [
    "__pycache__",
    "*.pyc",
    ".git",
    "tests/",
    ".pytest_cache",
    "*.log"
]

[cerebrium.deployment]
docker_base_image_url = ""  # Will use our custom Dockerfile
python_version = "3.9"
cuda_version = "11.8"
region = "us-east-1"

[cerebrium.scaling]
min_replicas = 0
max_replicas = 10
target_requests_per_replica = 10
scale_down_delay = "60s"

[cerebrium.hardware]
cpu = 2
memory = "8Gi"
gpu = "A40"
gpu_count = 1

[cerebrium.build]
dockerfile = "Dockerfile"

[cerebrium.env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"